export enum QuestionType {
    MULTIPLE_CHOICE = "MULTIPLE_CHOICE",
    TRUE_FALSE = "TRUE_FALSE",
    MULTIPLE_RESPONSE = "MULTIPLE_RESPONSE",
    FILL_IN_THE_BLANK = "FILL_IN_THE_BLANK",
    SINGLE_CHOICE = "SINGLE_CHOICE",
    MATCHING = "MATCHING",
    SHORT_ANSWER = "SHORT_ANSWER",
    ESSAY = "ESSAY"
}